App/urls.py
from django.urls import path
from App.views import *
urlpatterns = [
    path("login/",LoginApi.as_view(),name="login"),
    path("logout/",LogoutUserAPIView.as_view(),name="logout"),
    path("add-user/",AddUserAPIView.as_view(),name="add-user"),
    path("edit-user/",EditUserApi.as_view(),name="edit-user"),
    path('update-password/', ResetPasswordView.as_view(), name='change-password'),
    path('user-profile/', UserProfileAPIView.as_view(), name='user-profile'),
    path('market-coin/', MaketWatchScreenApi.as_view(), name='add-market-coin'),
    path('buy-sell-coin/', BuySellSellApi.as_view(), name='buy-sell-coin'),
    path('trade-history/', TradeHistoryApi.as_view(), name='trade-history'),
    path('user-coin-list/', CoinNameApi.as_view(), name='user-coin-list'),
    path('user-list/', UserListApiView.as_view(), name='user-list'),
    path("position/", PositionManager.as_view(), name="position"),
    path("position-view/", OpenPositionView.as_view(), name="position-view"),
    path("account-summary/", AccountSummaryApi.as_view(), name="account-summary"),
    path("position-coins/", PositionCoinsManager.as_view(), name="position-coins"),
    path("trade-particular-view/<str:id>", TradeParticularViewApi.as_view(), name="trade-particular-view/"),
    path("permission-toggle/", MyUserPerissionToggle.as_view(), name="permission-toggle"),
    path("change-passwordweb-api/", ChangePasswordWebAPI.as_view(), name="change-passwordweb-api"),
    path("get-admin-api/", GetAllAdminApiView.as_view(), name="get-admin-api"),
    path("get-master-api/", GetMasterApiView.as_view(), name="get-master-api"),
    path("limit-user-creation/", LimitUserCreation.as_view(), name="limit-user-creation"),
    path("admin-right/", AdminRightApi.as_view(), name="admin-right"),
    path("admin-right-get/", AdminRigthsGetApi.as_view(), name="admin-right-get"),
    path("admin-trade-right/", MarketTradeRight.as_view(), name="admin-trade-right"),
    path("admin-trade-get/", MarketTradeGetApi.as_view(), name="admin-trade-get"),
    path("brk/", BrkApi.as_view(), name="brk"),
    path("table-chart/", TableChartAPi.as_view(), name="table-chart"),
    path("pie-chart-api/", PieChartHandlerApi.as_view(), name="pie-chart-api"),
    path("child-user-api/", ChildUserFetchAPI.as_view(), name="child-user-api"),
    path("get-client-api/", GetAllClient.as_view(), name="get-client-api"),
    path("login-history/", LoginHistoryApi.as_view(), name="login-history"),
    # path("user-list/", UserListApi.as_view(), name="user-list"),
    path("search-user-api/", SearchUserAPI.as_view(), name="search-user-api"),
    path("script-quantity-api/", ScriptQuantityAPI.as_view(), name="script-quantity-api"),
    path("settlement-api/", SettlementReportApi.as_view(), name="settlement-api"),
    path("web-script-quantity-api/", WebScriptQuantityAPI.as_view(), name="web-script-quantity-api"),
    path("position-header-api/", PositionTopHeader.as_view(), name="position-header-api"),
    path("account-summary-credit-api/", AccountSummaryCreditAPI.as_view(), name="account-summary-credit-api"),
    path("master-child-api/", MasterChildApi.as_view(), name="master-child-api"),
    
    path("account-limit/", AccountLimitApi.as_view(), name="account-limit"),
    path("user-details-api/", UserDetailsAPIView.as_view(), name="user-details-api"),
    path("quantity-setting-api/", QuanityUpdateAllApi.as_view(), name="quantity-setting-api"),
    path("brk-setting-api/", BrokrageSettings.as_view(), name="brk-setting-api"),
    path("trademargin-setting-api/", TradeMarginSetting.as_view(), name="trademargin-setting-api"),
    path("trademargin-all-setting-api/", TradeMarginUpdateAllApi.as_view(), name="trademargin-all-setting-api"),
    path("intraday-squareoff-check/", IntradaySquareoffCheck.as_view(), name="intraday-squareoff-check"),
    path("weekly-admin-api/", WeeklyAdminListApi.as_view(), name="weekly-admin-api"),
    path("user-script-position-track/", UserScriptPositionTrack.as_view(), name="user-script-position-track"),
    path("delete-indentifer/", DeleteIndentifer.as_view(), name="delete-indentifer"),
    path("credit-submit/", CreditSubmitHandler.as_view(), name="credit-submit"),
    path("message-latest/", MessageGetLatest.as_view(), name="message-latest"),
    path("userbrkandprofitloss-handle/", UserBrkAndProfitLossAPI.as_view(), name="userbrkandprofitloss-handle"),
]

Web/urls.py
from django.contrib import admin
from django.urls import path, include
from Web.views import *

urlpatterns = [
    path("",LoginView.as_view(),name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("first-login", FirstLogin.as_view(), name="first-login"),
    path("change-password",ChangePasswordView.as_view(),name="change-password"),
    path("dashboard",Dashboard.as_view(),name="dashboard"),
    
    
    path("add-user",AddUserView.as_view(),name="add-user"),
    path("list-user",ListUserView.as_view(),name="list-user"),
    path("edit-user/<str:id>",EditUserView.as_view(),name="edit-user"),
    # path("account-limit",AccountLimitView.as_view(),name="account-limit"),
    
    
    path("download-csv",DownloadCSVView.as_view(),name="download-csv"),
    path("search-user",SearchUserView.as_view(),name="search-user"),
    path("search-all-user",SearchUsersView.as_view(),name="search-all-user"),
    
    
    path("user-deatils",UserDeatilsView.as_view(),name="user-deatils"),
    path("user-deatils-by-id/<str:id>",UserDeatilsViewById.as_view(),name="user-deatils-by-id"),
    path("tab-open-position/",OpenPositionView.as_view(),name="tab-open-position"),
    path("user-script/<str:id>",UserScriptMaster.as_view(),name="user-script"),
    
    path("group-setting",GropuSettingView.as_view(),name="group-setting"),
    path("script-quantity-setting",ScriptQuantitySetting.as_view(),name="script-quantity-setting"),
    path("tab-trade/<str:id>",TabTrades.as_view(),name="tab-trade"),
    
    
    path("quantity-setting/<str:id>",QuantitySettingView.as_view(),name="quantity-setting"),
    path("brk/<str:id>",BrkView.as_view(),name="brk"),
    path("trade-margin/<str:id>",TradeMarginTab.as_view(),name="trade-margin"),
    path("credit/<str:id>",CreditView.as_view(),name="credit"),
    path("tab-account-summary/<str:id>",TabAccountSummary.as_view(),name="tab-account-summary"),
    path("tab-settlement/<str:id>",TabSettlement.as_view(),name="tab-settlement"),
    path("rejection-log/<str:id>", RejectionLogView.as_view(), name="rejection-log"),
    path("share-deatils",ShareDetailsView.as_view(),name="share-deatils"),
    path("user-info/<str:id>",UserInfoView.as_view(),name="user-info"),
    
    
    path("market-watch",MarketWatchView.as_view(),name="market-watch"),
    path("sybols-watch",SybolsView.as_view(),name="sybols-watch"),
    path("trades",TradesView.as_view(),name="trades"),
    path("orders",OrdersView.as_view(),name="orders"),
    path("positions",PositionsView.as_view(),name="positions"),
    path("profit-and-loss",ProfitAndLoss.as_view(),name="profit-and-loss"),
    path("m2m-profit-and-loss",M2MProfitAndLoss.as_view(),name="m2m-profit-and-loss"),
    path("intraday-history",IntradayHistory.as_view(),name="intraday-history"),
    path("rejection-log",RejectionLogTab.as_view(),name="rejection-log"),
    path("login-history",LoginHistory.as_view(),name="login-history"),
    
    
    path("open-position",OpenPosition.as_view(),name="open-position"),
    path("manage-trades",ManageTrades.as_view(),name="manage-trades"),
    path("trade-account",TradeAccount.as_view(),name="trade-account"),
    path("settlement",SettlementView.as_view(),name="settlement"),
    path("account-summary",AccountSummary.as_view(),name="account-summary"),
    path("bill-generate",BillGenerate.as_view(),name="bill-generate"),
    path("trades-margins",TradeMargin.as_view(),name="trades-margins"),
    path("script-master",ScriptMaster.as_view(),name="script-master"),
    path("logs-history",LogsHistory.as_view(),name="logs-history"),
    path("user-logs-new",UserLogsNew.as_view(),name="user-logs-new"),
    path("user-script-position-track",UserScriptPositionTrack.as_view(),name="user-script-position-track"),
    path("position-track-view-orders",PositionTrackViewOrders.as_view(),name="position-track-view-orders"),
    path("user-script-position-trac-pl",UserScriptPositionTrackPl.as_view(),name="user-script-position-trac-pl"),
    path("script-quantity",ScriptQuantity.as_view(),name="script-quantity"),
    path("weekly-admin",WeeklyAdminView.as_view(),name="weekly-admin"),
    
    
    
    path("exchange-time",ExchangeTimeSchedule.as_view(),name="exchange-time"),
    path("message",MassageView.as_view(),name="message"),
    
    
#----------------------csv download ---------------------#

    path('rejection-csv/<str:id>/', RejectionDownloadCSVView.as_view(), name='rejection-csv'),
    path('trade-csv/<str:id>/', TradeDownloadCsv.as_view(), name='trade-csv'),
    path('credit-csv/<str:id>/', CreditDownloadCSVView.as_view(), name='credit-csv'),
    path('account-summary-tab-csv/<str:id>/', AccountSummaryTabDownloadCSV.as_view(), name='account-summary-tab-csv'),
    path('account-summary-csv/<str:id>/', AccountSummaryDownloadCSV.as_view(), name='account-summary-csv'),
    path('manage-trades-csv/', TradesDownloadCSVView.as_view(), name='manage-trades-csv'),
    path('view-trades-csv/', ViewTradesDownloadCSV.as_view(), name='view-trades-csv'),
    path('order-csv-download/', OrderDownloadCSVView.as_view(), name='order-csv-download'),
    path('open-position-view/', OpenPositionView.as_view(), name='open-position-view'),

]

quickTradeBackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include("App.urls")),
    path("",include(("Web.urls", "Admin"), namespace="Admin")),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/view/M2Mprofit-loss.html
{% extends "index.html" %} {% block content %}


<div class="tab-content" id="m2mpnl">
    <div class="flex">
        <div class="trade-download">
            <div style="transform: rotate(90deg);padding-left: 10px;">
                <p>Filter</p>
            </div>
            {% comment %} <span>
                <a href=""><i class="fa-solid fa-file-csv"></i></a>
            </span> {% endcomment %}
        </div>
        <div class="trades-side">
            <div class="trade-top">
                <div class="flex space-bw">
                    <div>
                        <p>Filter</p>
                    </div>
                    <div class="closeBtn">
                        <i class="fa-solid fa-xmark"></i>
                    </div>
                </div>
            </div>
            <form method="get">
                {% csrf_token %}
            <div class="trade-btm">
                <div>
                    <label for="">Username:</label>
                    <select  id="m2mUserNameId">
                        <option value="">All Users</option>
                        {% for i in user_obj %}
                            <option value="{{i.user_name}}">{{i.user_name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <label for=""></label>
                    <button type="button" id="m2mBtnId" class="form-btn">Apply</button>
                    <a href="{% url 'Admin:m2m-profit-and-loss' %}" style="color:#fff !important;padding: 2px 10px; cursor:pointer;" class="cancel-btn">Clear</a>
                </div>
            </div>
        </form>
        </div>
        <div class="trades-body user-table">
            <table style="width: 100%;">
                <tr>
                    <th>User</th>
                    <th>User Type</th>
                    <th>Profit / Loss</th>
                    <th>PL Share(%)</th>
                    <th>PL Share Amount</th>
                </tr>
                <tbody id="m2mPnLId">
                    <tr>
                        <td>User</td>
                        <td>User Type</td>
                        <td>Profit / Loss</td>
                        <td>PL Share(%)</td>
                        <td>PL Share Amount</td>
                    </tr>
                </table>
            </table>
        </div>
    </div>
</div>

<script>

    const m2mProfitHandler = (user_ ,user_id = "{{user.id}}") =>{

        let m2mListUserWise = [];
        axios.get(`{% url "weekly-admin-api" %}?user_id=${user_id}&user_name=${user_name}`, {headers: { "X-CSRFToken": "{{ csrf_token }}" }})
        .then(res => {
            console.log("res ==", res);
            $("#m2mPnLId").empty();
            if (res?.data?.result) {
                  axios
                    .post(`${BASE_URL}/api/tradeCoin/weekly`, {
                      identifiers: res?.data?.result?.map(
                        (obj) => obj.identifer
                      ),
                    })
                    .then((res1) => {
                      res?.data?.result.map((mapItem) => {
                          const currentLiveData = res1.data?.response?.find(
                            (liveData) =>
                              liveData?.InstrumentIdentifier === mapItem?.identifer
                          );
                          const currentP_L =
                            mapItem?.total_quantity > 0
                              ? (currentLiveData?.BuyPrice - mapItem?.avg_buy_price) *
                                mapItem?.total_quantity *
                                currentLiveData?.QuotationLot
                              : (mapItem?.avg_sell_price - currentLiveData?.SellPrice) *
                                Math.abs(mapItem?.total_quantity) *
                                currentLiveData?.QuotationLot;
    
                            m2mListUserWise = [
                            ...(m2mListUserWise || []),
                            {
                              user_id: mapItem?.buy_sell_user__id,
                              m2mTotal: currentP_L,
                            },
                          ];
                      });
                    })
            }
    
            setTimeout(() => {
                res.data.release_p_and_l.map(item => {
                    const filterUser = m2mListUserWise?.filter(obj => obj.user_id === item.user_summary__id)
                    const m2mFinal =  Number(
                        filterUser && filterUser.length === 0
                          ? 0
                          : filterUser.length === 1
                          ? filterUser?.[0]?.m2mTotal?.toFixed(2)
                          : filterUser?.reduce((a, b) => a?.m2mTotal || 0 + b?.m2mTotal || 0)
                      )?.toFixed(2);
                    $("#m2mPnLId").append(`
                        <tr>
                            <td>${item.user_summary__user_name}</td>
                            <td>${item.user_summary__user_type}</td>
                            <td style="color:${item.total_amount >=0 ? 'blue':'red'};">${item.total_amount.toFixed(2)}</td>
                            <td style="color:${m2mFinal >=0 ? 'blue':'red'};">${m2mFinal}</td> 
                            <td style="color: ${(Number(m2mFinal) + Number(item.total_amount)) >= 0 ? 'blue' : 'red'};">${(Number(m2mFinal) +Number(item.total_amount))?.toFixed(2)}</td>
                        </tr>
                    `);
                });
            }, 1000)
        })
        .catch(err => {
            console.log("err", err);
        });
    }
    m2mProfitHandler();

    $("#m2mBtnId").click(() => {
        m2mProfitHandler($("#m2mUserNameId").val());
      })
</script>

{% endblock content %}

templates/view/login-history.html
{% extends "index.html" %} {% block content %}


<div class="tab-content" id="login">
    <div class="flex">
        <div class="trade-download">
            <div style="transform: rotate(90deg);padding-left: 10px; cursor: pointer;">
                <p id="loginHistoryId">Filter</p>
            </div>
            <a href="{% url 'Admin:login-history' %}?from_date={{ from_date }}&to_date={{ to_date }}&exchange={{ exchange }}&symbol={{ symbol }}&download_csv=true" class="download-csv-link">
                <i class="fa-solid fa-file-csv"></i>
            </a>
        </div>
        <div class="trades-side">
            <div class="trade-top">
                <div class="flex space-bw">
                    <div>
                        <p>Filter</p>
                    </div>
                    <div class="closeBtn">
                        <i class="fa-solid fa-xmark"></i>
                    </div>
                </div>
            </div>
            <form method="get">
                {% csrf_token %}
                <div class="trade-btm">
                    <div>
                        <label for="">From:</label>
                        <input type="date" name="from_date" >
                    </div>
                    <div>
                        <label for="">Date:</label>
                        <input type="date" name="to_date" >
                    </div>
                    <div>
                        <label for="">Username:</label>

                        <select name="user_name" >
                            {% for i in user_names %}
                            <option value="{{i.user_name}}">{{i.user_name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    {% comment %} <div>
                        <label for="">Search:</label>
                        <input type="text">
                    </div> {% endcomment %}
                    <div>
                        <label for=""></label>
                        <button type="submit" value="View" class="form-btn">View</button>
                        <a href="{% url 'Admin:login-history' %}" style="background-color:#646464; color:#fff !important;" type="" value="View" class="form-btn">Clear</a>
                    </div>
                </div>
            </form>
        </div>
        <div class="trades-body user-table">
            {% if login_data %}
            <table style="width: 100%;">
                <tr>
                    <th>Login Date</th>
                    <th>Logout Date</th>
                    <th>Username</th>
                    <th>User Type</th>
                    <th>IP Address</th>
                    <th>Device ID</th>
                   
                </tr>
                {% for i in login_data %}
                <tr>
                    <td>{{i.created_at}}</td>
                    <td>{{i.action}}</td>
                    <td>{{i.user_history__user_name}}</td>
                    <td>{{i.user_history__user_type}}</td>
                    <td>{{i.ip_address}}</td>
                    <td>{{i.method}}</td>
                   
                </tr>
                {% endfor %}
            </table>
            {% else %}
            <div style="display: flex;justify-content: center;margin-top: 14%;">
              <p>No data found</p>
            </div>
        {% endif %}
        </div>
    </div>
</div>

<script>
    $('.user-deatils').click(function () {
        $(".trades-side").hide();
        $(".trades-body").css("width", "100%");
    });
    
    $('#loginHistoryId').click(function () {
      $(".trades-side").show();
      $(".trades-body").css("width", "79%");
    });
</script>

{% endblock content %}

templates/view/order.html
{% extends "index.html" %} {% block content %}

<div class="tab-content" id="orders">
    <div class="flex">
        <div class="trade-download">
            <div style="transform: rotate(90deg);padding-left: 10px;">
                <p id="orderFilterId">Filter</p>
            </div>
            <a href="{% url 'Admin:order-csv-download' %}?from_date={{ from_date }}&to_date={{ to_date }}&exchange={{ exchange }}&symbol={{ symbol }}&download_csv=true" class="download-csv-link">
                <i class="fa-solid fa-file-csv"></i>
            </a>
        </div>
        <div class="trades-side">

            <div class="trade-top">
                <div class="flex space-bw">
                    <div>
                        <p>Filter</p>
                    </div>
                    <div class="closeBtn">
                        <i class="fa-solid fa-xmark"></i>
                    </div>
                </div>
            </div>
            <form method="get">
                {% csrf_token %}
                <div class="trade-btm">
                    <div>
                        <label for="">From:</label>
                        <input name="from_date" type="date">
                    </div>
                    <div>
                        <label for="">To:</label>
                        <input name="to_date" type="date">
                    </div>
                    <div>
                        <label for="">Username:</label>
                        <select name="user_name">
                            <option value="">All Users</option>
                            {% for i in user_list  %}
                                <option value="{{ i.user_name }}">{{ i.user_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div>
                        <label for="">Exchange:</label>
                        {% comment %} <select name="exchange" class="form_control">
                          <option value="">All Exchange</option>
                          {% for symbol in exchange_obj %}
                            {% if symbol.symbol_name == "NSE" and symbol.exchange %}
                              <option value="NSE">NSE</option>
                            {% elif symbol.symbol_name == "MCX" and symbol.exchange %}
                              <option value="MCX">MCX</option>
                            {% elif symbol.symbol_name == "MINI" and symbol.exchange %}
                              <option value="MINI">MINI</option>
                            {% endif %}
                        {% endfor %}
                        </select> {% endcomment %}
                        <select name="ex_change">
                            <option value="">All Exchanges</option>
                            <option value="MCX">MCX</option>
                            <option value="NSE">NSE</option>
                            <option value="MINI">MINI</option>
                        </select>
                    </div>
                    <div>
                        <label for="">Symbols:</label>
                        <select name="coin_name" id="coin_name">
                            <option value="">All Symbols</option>
                            {% for coin in user_coin_names %}
                                <option value="{{ coin.coin_name }}">{{ coin.coin_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div>
                        <label for=""></label>
                        <button type="submit" value="View" class="form-btn">View</button>
                        <a style="color:#fff ! important; padding:2px" href="{% url 'Admin:orders' %}" value="Clear" class="cancel-btn">Clear</a>
                    </div>
                </div>
            </form>
        </div>
        <div class="trades-body user-table">
            {% if response %}
            <table style="width: 100%;">
                <tr>
                    <th>Username</th>
                    <th>Symbol</th>
                    <th>Type</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Order Time</th> 
                    <th>Ip Address</th>
                    {% comment %} <th>Device id</th>
                    <th>Reference Price</th> {% endcomment %}
                    <th>Order Method</th>
                </tr>
                {% for i in response %}
                <tr>
                    <td>{{i.buy_sell_user__user_name}}</td>
                    <td>{{i.coin_name}}</td>
                    <td {% if i.quantity > 0 %}style="color: blue;"{% else %}style="color: red;"{% endif %}>{{ i.action }}</td>
                    <td {% if i.quantity > 0 %}style="color: blue;"{% else %}style="color: red;"{% endif %}>{{ i.quantity |stringformat:"+d"|slice:"1:"}}</td>
                    <td>{{i.price}}</td>
                    <td>{{i.created_at}}</td>
                    <td>{{i.ip_address}}</td>
                    {% comment %} <td>Device id</td>
                    <td>Refernce</td> {% endcomment %}
                    <td>{{i.order_method}}</td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
            <div style="display: flex;justify-content: center;margin-top: 14%;">
              <p>No data found</p>
            </div>
        {% endif %}
        </div>
    </div>
</div>
<script>
    $('.closeBtn').click(function () {
        $(".trades-side").hide();
        $(".trades-body").css("width", "95%");
    });
    
    $('#orderFilterId').click(function () {
        $(".trades-side").show();
        $(".trades-body").css("width", "79%");
    });
</script>

{% endblock content %}

templates/view/trades.html
{% extends "index.html" %} {% block content %}

<div class="tab-content" id="trades">
    <div class="flex">
        <div class="trade-download">
            <div style="transform: rotate(90deg);padding-left: 10px;">
                <p style="cursor: pointer;" id="tradesFilerID">Filter</p>
            </div>
            <span>
                <a href="{% url 'Admin:view-trades-csv' %}"><i class="fa-solid fa-file-csv"></i></a>
            </span>
        </div>
        <div class="trades-side">
            <div class="trade-top">
                <div class="flex space-bw">
                    <div>
                        <p>Filter</p>
                    </div>
                    <div class="closeBtn">
                        <i class="fa-solid fa-xmark"></i>
                    </div>
                </div>
            </div>
            <form method="get">
                {% csrf_token %}
                <div class="trade-btm">
                    <div>
                        <label for="">From:</label>
                        <input name="from_date" type="date">
                    </div>
                    <div>
                        <label for="">To:</label>
                        <input name="to_date" type="date">
                    </div>
                    <div>
                        <label for="">Username:</label>
                        <select name="user_name">
                            <option value="">All Users</option>
                            {% for i in user_list  %}
                                <option value="{{ i.user_name }}">{{ i.user_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div>
                        <label for="">Exchange:</label>
                        <select name="ex_change" >
                            <option value="">All Exchanges</option>
                            <option value="MCX">MCX</option>
                            <option value="NSE">NSE</option>
                            <option value="MINI">MINI</option>
                        </select>
                    </div>
                    <div>
                    <label for="coin_name">Symbols:</label>
                    <select name="coin_name" id="coin_name">
                        <option value="">All Symbols</option>
                        {% for coin in user_coin_names %}
                            <option value="{{ coin.coin_name }}">{{ coin.coin_name }}</option>
                        {% endfor %}
                    </select>

                    </div>
                    <div>
                        <label for=""></label>
                        <button type="submit" value="View" class="form-btn">View</button>
                        <a style="color:#fff !important; padding: 2px;" href="{% url 'Admin:trades' %}" value="Clear" class="cancel-btn">Clear</a>
                    </div>
                </div>
            </form>
        </div>
        <div class="trades-body user-table">
            {% if response %}
            <table style="width: 100%;">
                <tr>
                    <th>Execution Time</th>
                    <th>Username</th>
                    <th>Symbol</th>
                    <th>Type</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Order Time</th>
                    <th>Ip Address</th>
                    {% comment %} <th>Refernce</th> {% endcomment %}
                    <th>Order Method</th>
                </tr>
                {% for i in response %}
                <tr>
                    <td>{{i.created_at}}</td>
                    <td>{{i.buy_sell_user__user_name}}</td>
                    <td style="color: {% if i.action == 'SELL' %}red{% else %}blue{% endif %};">{{i.coin_name}}</td>
                    <td style="color: {% if i.action == 'SELL' %}red{% elif i.action == 'BUY' %}blue{% else %}inherit{% endif %};">{{i.action}}</td>
                    <td style="color: {% if i.action == 'SELL' %}red{% else %}blue{% endif %};" id="quanity{{i.id}}">{% if i.quantity > 0 %} {{i.quantity}} {% else %} {{ i.quantity|stringformat:"+d"|slice:"1:" }} {% endif %}</td>
                    <td style="color: {% if i.action == 'SELL' %}red{% else %}blue{% endif %};" id="price{{i.id}}">{{i.price}}</td>
                    <td>{{i.created_at}}</td>
                    <td>{{i.ip_address}}</td>
                    {% comment %} <td>Refernce</td> {% endcomment %}
                    <td>{{i.order_method}}</td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
            <div style="display: flex;justify-content: center;margin-top: 14%;">
              <p>No data found</p>
            </div>
        {% endif %}
        </div>
    </div>
</div>

<script>

    $('.closeBtn').click(function () {
        $(".trades-side").hide();
        $(".trades-body").css("width", "95%");
    });
    
    $('#tradesFilerID').click(function () {
        $(".trades-side").show();
        $(".trades-body").css("width", "79%");
    });

</script>

{% endblock content %}