App/urls.py
from django.urls import path
from App.views import *
urlpatterns = [
    path("login/",LoginApi.as_view(),name="login"),
    path("logout/",LogoutUserAPIView.as_view(),name="logout"),
    path("add-user/",AddUserAPIView.as_view(),name="add-user"),
    path("edit-user/",EditUserApi.as_view(),name="edit-user"),
    path('update-password/', ResetPasswordView.as_view(), name='change-password'),
    path('user-profile/', UserProfileAPIView.as_view(), name='user-profile'),
    path('market-coin/', MaketWatchScreenApi.as_view(), name='add-market-coin'),
    path('buy-sell-coin/', BuySellSellApi.as_view(), name='buy-sell-coin'),
    path('trade-history/', TradeHistoryApi.as_view(), name='trade-history'),
    path('user-coin-list/', CoinNameApi.as_view(), name='user-coin-list'),
    path('user-list/', UserListApiView.as_view(), name='user-list'),
    path("position/", PositionManager.as_view(), name="position"),
    path("position-view/", OpenPositionView.as_view(), name="position-view"),
    path("account-summary/", AccountSummaryApi.as_view(), name="account-summary"),
    path("position-coins/", PositionCoinsManager.as_view(), name="position-coins"),
    path("trade-particular-view/<str:id>", TradeParticularViewApi.as_view(), name="trade-particular-view/"),
    path("permission-toggle/", MyUserPerissionToggle.as_view(), name="permission-toggle"),
    path("change-passwordweb-api/", ChangePasswordWebAPI.as_view(), name="change-passwordweb-api"),
    path("get-admin-api/", GetAllAdminApiView.as_view(), name="get-admin-api"),
    path("get-master-api/", GetMasterApiView.as_view(), name="get-master-api"),
    path("limit-user-creation/", LimitUserCreation.as_view(), name="limit-user-creation"),
    path("admin-right/", AdminRightApi.as_view(), name="admin-right"),
    path("admin-right-get/", AdminRigthsGetApi.as_view(), name="admin-right-get"),
    path("admin-trade-right/", MarketTradeRight.as_view(), name="admin-trade-right"),
    path("admin-trade-get/", MarketTradeGetApi.as_view(), name="admin-trade-get"),
    path("brk/", BrkApi.as_view(), name="brk"),
    path("table-chart/", TableChartAPi.as_view(), name="table-chart"),
    path("pie-chart-api/", PieChartHandlerApi.as_view(), name="pie-chart-api"),
    path("child-user-api/", ChildUserFetchAPI.as_view(), name="child-user-api"),
    path("get-client-api/", GetAllClient.as_view(), name="get-client-api"),
    path("login-history/", LoginHistoryApi.as_view(), name="login-history"),
    # path("user-list/", UserListApi.as_view(), name="user-list"),
    path("search-user-api/", SearchUserAPI.as_view(), name="search-user-api"),
    path("script-quantity-api/", ScriptQuantityAPI.as_view(), name="script-quantity-api"),
    path("settlement-api/", SettlementReportApi.as_view(), name="settlement-api"),
    path("web-script-quantity-api/", WebScriptQuantityAPI.as_view(), name="web-script-quantity-api"),
    path("position-header-api/", PositionTopHeader.as_view(), name="position-header-api"),
    path("account-summary-credit-api/", AccountSummaryCreditAPI.as_view(), name="account-summary-credit-api"),
    path("master-child-api/", MasterChildApi.as_view(), name="master-child-api"),
    
    path("account-limit/", AccountLimitApi.as_view(), name="account-limit"),
    path("user-details-api/", UserDetailsAPIView.as_view(), name="user-details-api"),
    path("quantity-setting-api/", QuanityUpdateAllApi.as_view(), name="quantity-setting-api"),
    path("brk-setting-api/", BrokrageSettings.as_view(), name="brk-setting-api"),
    path("trademargin-setting-api/", TradeMarginSetting.as_view(), name="trademargin-setting-api"),
    path("trademargin-all-setting-api/", TradeMarginUpdateAllApi.as_view(), name="trademargin-all-setting-api"),
    path("intraday-squareoff-check/", IntradaySquareoffCheck.as_view(), name="intraday-squareoff-check"),
    path("weekly-admin-api/", WeeklyAdminListApi.as_view(), name="weekly-admin-api"),
    path("user-script-position-track/", UserScriptPositionTrack.as_view(), name="user-script-position-track"),
    path("delete-indentifer/", DeleteIndentifer.as_view(), name="delete-indentifer"),
    path("credit-submit/", CreditSubmitHandler.as_view(), name="credit-submit"),
    path("message-latest/", MessageGetLatest.as_view(), name="message-latest"),
    path("userbrkandprofitloss-handle/", UserBrkAndProfitLossAPI.as_view(), name="userbrkandprofitloss-handle"),
]

Web/urls.py
from django.contrib import admin
from django.urls import path, include
from Web.views import *

urlpatterns = [
    path("",LoginView.as_view(),name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("first-login", FirstLogin.as_view(), name="first-login"),
    path("change-password",ChangePasswordView.as_view(),name="change-password"),
    path("dashboard",Dashboard.as_view(),name="dashboard"),
    
    
    path("add-user",AddUserView.as_view(),name="add-user"),
    path("list-user",ListUserView.as_view(),name="list-user"),
    path("edit-user/<str:id>",EditUserView.as_view(),name="edit-user"),
    # path("account-limit",AccountLimitView.as_view(),name="account-limit"),
    
    
    path("download-csv",DownloadCSVView.as_view(),name="download-csv"),
    path("search-user",SearchUserView.as_view(),name="search-user"),
    path("search-all-user",SearchUsersView.as_view(),name="search-all-user"),
    
    
    path("user-deatils",UserDeatilsView.as_view(),name="user-deatils"),
    path("user-deatils-by-id/<str:id>",UserDeatilsViewById.as_view(),name="user-deatils-by-id"),
    path("tab-open-position/",OpenPositionView.as_view(),name="tab-open-position"),
    path("user-script/<str:id>",UserScriptMaster.as_view(),name="user-script"),
    
    path("group-setting",GropuSettingView.as_view(),name="group-setting"),
    path("script-quantity-setting",ScriptQuantitySetting.as_view(),name="script-quantity-setting"),
    path("tab-trade/<str:id>",TabTrades.as_view(),name="tab-trade"),
    
    
    path("quantity-setting/<str:id>",QuantitySettingView.as_view(),name="quantity-setting"),
    path("brk/<str:id>",BrkView.as_view(),name="brk"),
    path("trade-margin/<str:id>",TradeMarginTab.as_view(),name="trade-margin"),
    path("credit/<str:id>",CreditView.as_view(),name="credit"),
    path("tab-account-summary/<str:id>",TabAccountSummary.as_view(),name="tab-account-summary"),
    path("tab-settlement/<str:id>",TabSettlement.as_view(),name="tab-settlement"),
    path("rejection-log/<str:id>", RejectionLogView.as_view(), name="rejection-log"),
    path("share-deatils",ShareDetailsView.as_view(),name="share-deatils"),
    path("user-info/<str:id>",UserInfoView.as_view(),name="user-info"),
    
    
    path("market-watch",MarketWatchView.as_view(),name="market-watch"),
    path("sybols-watch",SybolsView.as_view(),name="sybols-watch"),
    path("trades",TradesView.as_view(),name="trades"),
    path("orders",OrdersView.as_view(),name="orders"),
    path("positions",PositionsView.as_view(),name="positions"),
    path("profit-and-loss",ProfitAndLoss.as_view(),name="profit-and-loss"),
    path("m2m-profit-and-loss",M2MProfitAndLoss.as_view(),name="m2m-profit-and-loss"),
    path("intraday-history",IntradayHistory.as_view(),name="intraday-history"),
    path("rejection-log",RejectionLogTab.as_view(),name="rejection-log"),
    path("login-history",LoginHistory.as_view(),name="login-history"),
    
    
    path("open-position",OpenPosition.as_view(),name="open-position"),
    path("manage-trades",ManageTrades.as_view(),name="manage-trades"),
    path("trade-account",TradeAccount.as_view(),name="trade-account"),
    path("settlement",SettlementView.as_view(),name="settlement"),
    path("account-summary",AccountSummary.as_view(),name="account-summary"),
    path("bill-generate",BillGenerate.as_view(),name="bill-generate"),
    path("trades-margins",TradeMargin.as_view(),name="trades-margins"),
    path("script-master",ScriptMaster.as_view(),name="script-master"),
    path("logs-history",LogsHistory.as_view(),name="logs-history"),
    path("user-logs-new",UserLogsNew.as_view(),name="user-logs-new"),
    path("user-script-position-track",UserScriptPositionTrack.as_view(),name="user-script-position-track"),
    path("position-track-view-orders",PositionTrackViewOrders.as_view(),name="position-track-view-orders"),
    path("user-script-position-trac-pl",UserScriptPositionTrackPl.as_view(),name="user-script-position-trac-pl"),
    path("script-quantity",ScriptQuantity.as_view(),name="script-quantity"),
    path("weekly-admin",WeeklyAdminView.as_view(),name="weekly-admin"),
    
    
    
    path("exchange-time",ExchangeTimeSchedule.as_view(),name="exchange-time"),
    path("message",MassageView.as_view(),name="message"),
    
    
#----------------------csv download ---------------------#

    path('rejection-csv/<str:id>/', RejectionDownloadCSVView.as_view(), name='rejection-csv'),
    path('trade-csv/<str:id>/', TradeDownloadCsv.as_view(), name='trade-csv'),
    path('credit-csv/<str:id>/', CreditDownloadCSVView.as_view(), name='credit-csv'),
    path('account-summary-tab-csv/<str:id>/', AccountSummaryTabDownloadCSV.as_view(), name='account-summary-tab-csv'),
    path('account-summary-csv/<str:id>/', AccountSummaryDownloadCSV.as_view(), name='account-summary-csv'),
    path('manage-trades-csv/', TradesDownloadCSVView.as_view(), name='manage-trades-csv'),
    path('view-trades-csv/', ViewTradesDownloadCSV.as_view(), name='view-trades-csv'),
    path('order-csv-download/', OrderDownloadCSVView.as_view(), name='order-csv-download'),
    path('open-position-view/', OpenPositionView.as_view(), name='open-position-view'),

]

quickTradeBackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include("App.urls")),
    path("",include(("Web.urls", "Admin"), namespace="Admin")),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/header.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <div class="main-box-head">
        <img class="head-logo" src="{% static 'images/arex.png' %}" alt="app icon">
        <label>Quick Trade [{{request.user.user_name}}-{{request.user.user_type}}]</label>
    </div>
    <div class="tab-head">
        <li class="active open-file-menu" data-id="users">File
            <ul class="view-dropdown" id="file-dropdown">
                <li onClick="changePasswordOpen()"><a class="fa-solid fa-key"></a>Change Password</li>
                <li data-id="logoutaccount"><a href="{% url 'Admin:logout' %}"><i class="fa-solid fa-right-from-bracket"></i>Logout</a></li>
            </ul>
        </li>
    <li data-id="dashboard"><a href="{% url 'Admin:dashboard' %}">Dashboard</a></li>
    {% if request.user.user_type != "Client" %}
        <li data-id="users" class="user-view-dropdown">Users
            <ul class="view-dropdown" id="user-dropdown">
                <li data-id="create-user"><a href="{% url 'Admin:add-user' %}"><i class="fa-solid fa-user"></i>Create User</a></li>
                <li data-id="user-list"><a href="{% url 'Admin:list-user' %}"><i class="fa-solid fa-list"></i>User List</a></li>
                <li data-id="search-user"><a href="{% url 'Admin:search-user' %}"><i class="fa-solid fa-magnifying-glass"></i>Search User</a></li>
            </ul>
        </li>
    {% endif %}
      <li data-id="View" class="open-view-menu">View</i>
        <ul class="view-dropdown" id="view-dropdown">
            <li data-id="marketwatch"><a href="{% url 'Admin:market-watch' %}"><i class="fa-solid fa-right-left fa-rotate-90"></i>Market Watch</a></li>
            <li data-id="trades"><a href="{% url 'Admin:trades' %}"><i class="fa-solid fa-file"></i>Trades</a></li>
            <li data-id="orders"><a href="{% url 'Admin:orders' %}"><i class="fa-solid fa-file"></i>Order</a></li>
            <li data-id="position"><a href="{% url 'Admin:positions' %}"><i class="fa-solid fa-map"></i>Positions</a></li>
            <li data-id="pnl"><a href="{% url 'Admin:profit-and-loss' %}"><i class="fa-solid fa-chart-line"></i>Profit and Loss</a></li>
            <li data-id="m2mpnl"><a href="{% url 'Admin:m2m-profit-and-loss' %}"><i class="fa-solid fa-chart-line"></i>M2M Profit and Loss</a></li>
            {% comment %} <li data-id="intraday"><a href="{% url 'Admin:intraday-history' %}"><i class="fa-solid fa-file-circle-xmark"></i>Intraday History</a></li> {% endcomment %}
            <li data-id="rejection"><a href="{% url 'Admin:rejection-log' %}"><i class="fa-solid fa-file-circle-xmark"></i>Rejection Log</a></li>
            <li data-id="login"><a href="{% url 'Admin:login-history' %}"><i class="fa-solid fa-file-circle-question"></i>Login History</a></li>
        </ul>
      </li>
      <li data-id="report" class="open-report-menu">Report</i>
        <ul class="view-dropdown" id="report-dropdown">
            <li data-id="openposition"><a href="{% url 'Admin:open-position' %}"><i class="fa-solid fa-chart-line"></i>Open Position</a></li>
            <li data-id="managetrades"><a href="{% url 'Admin:manage-trades' %}"><i class="fa-solid fa-list-check"></i>Manage Trades</a></li>
            <li data-id="tradeaccount"><a href="{% url 'Admin:trade-account' %}"><i class="fa-solid fa-file-invoice"></i>Trade Account</a></li>
            <li data-id="settlement"><a href="{% url 'Admin:settlement' %}"><i class="fa-solid fa-handshake"></i>Settlement</a></li>
            <li data-id="accountsummary"><a href="{% url 'Admin:account-summary' %}"><i class="fa-solid fa-window-maximize"></i>Account Summary</a></li>
            {% comment %} <li data-id="billgenerate"><a href="{% url 'Admin:bill-generate' %}"><i class="fa-solid fa-money-bill-1-wave"></i>Bill Generate</a></li> {% endcomment %}
            <li data-id="billgenerate"><a href="{% url 'Admin:weekly-admin' %}"><i class="fa-solid fa-gear"></i>Weekly Admin</a></li>
            <li data-id="trades-margins"><a href="{% url 'Admin:trades-margins' %}"><i class="fa-brands fa-stack-overflow"></i>Trade Margin</a></li>
            <li data-id="trades-margins"><a href="{% url 'Admin:script-master' %}"><i class="fa-solid fa-money-bill-1-wave"></i>Script Master</a></li>
            {% comment %} <li data-id="logshistory"><a href="{% url 'Admin:logs-history' %}"><i class="fa-solid fa-file-circle-question"></i>Logs History</a></li> {% endcomment %}
            {% comment %} <li data-id="logsnew"><a href="{% url 'Admin:user-logs-new' %}"><i class="fa-solid fa-users"></i>User Logs New</a></li> {% endcomment %}
            <li data-id="positiontrack"><a href="{% url 'Admin:user-script-position-track' %}"><i class="fa-solid fa-chalkboard-user"></i>User Script Position Track</a></li>
            {% comment %} <li data-id="positionpl"><a href="{% url 'Admin:user-script-position-trac-pl' %}"><i class="fa-solid fa-chart-simple"></i>User Script Position PL</a></li> {% endcomment %}
            <li data-id="scriptquantity"><a href="{% url 'Admin:script-quantity' %}"><i class="fa-solid fa-scroll"></i>Script Quantity</a></li>
        </ul>
      </li>
      <li data-id="tools" class="open-tools-menu">Tools</i>
        <ul class="view-dropdown" id="tools-dropdown">
            <li data-id="scriptquantity"><a href="{% url 'Admin:message' %}"><i class="fa-solid fa-scroll"></i>Message</a></li>
            <li data-id="scriptquantity"><a href="{% url 'Admin:exchange-time' %}"><i class="fa-solid fa-scroll"></i>Exchange Time Schedule</a></li>
        </ul>
      </li><br>

      <div style="margin-left: 1%; display: flex; justify-content: flex-left;">
        <div style='position:relative;' class='icon-container'>
            <a href="{% url 'Admin:market-watch' %}"><img src="{% static 'images/watch.png' %}" alt="Arrow Image"></a>
            <span class='tooltip'>Market Watch</span>
        </div>
        <div style='position:relative;' class='icon-container'>
            <a href="{% url 'Admin:trades' %}"><img src="{% static 'images/trade.png' %}" alt="Solid Book Image"></a>
            <span class='tooltip' style="right: -20px;">Trades</span>
        </div>
        <div style='position:relative;' class='icon-container'>
            <a href="{% url 'Admin:orders' %}"><img src="{% static 'images/order.png' %}" alt="Chart Image"></a>
            <span class='tooltip' style="right: -25px;">Orders</span>
        </div>
        <div style='position:relative;' class='icon-container'>
            <a href="{% url 'Admin:positions' %}"><img src="{% static 'images/position.png' %}" alt="Regular Book Image"></a>
            <span class='tooltip' style="right: -25px;">Positions</span>
        </div>
        {% if request.user.user_type != "Client" %}
        <div style='position:relative;' class='icon-container'>
            <a href="{% url 'Admin:add-user' %}"><img src="{% static 'images/adduser.png' %}" alt="User Plus Image"></a>
            <span class='tooltip' style="right: -30px;">Add User</span>
        </div>
        <div style='position:relative;' class='icon-container'>
            <a href="{% url 'Admin:search-user' %}"><img src="{% static 'images/searchuser.png' %}" alt="User Plus Image"></a>
            <span class='tooltip' style="right: -40px;">Search User</span>
        </div>
        {% endif %}
      </div>
    </div>
  </body>
  <style>
    * main css  */
    .tab-content {
        display: none;
    }

    .tab-content:first-of-type {
        display: block;
    }

    .tab-head {
        border-bottom: 1px solid #D3D3D3;
    }

    .head-logo {
        height: 22px;
        padding-right: 5px;
        padding-top: 5px;
    }
    .main-box-head {
        display: flex;
        align-item: center;
        padding-left: 10px;
    }
    .tab-head li {
        display: inline-block;
        padding: 5px 15px;
        position: relative;
        margin-right: 5px;
        cursor: pointer;
        font-size: 15px;
    }

    .tab-head li i {
        margin-left: 5px;
        font-size: 12px;
    }

    .tab-head li.active {
        background: #d9d9d9;
        color: #000;
    }

    ul.dropdown,
    ul.view-dropdown {
        position: absolute;
        display: block;
        background: #fff;
        z-index: 999;
        width: 130px;
        top: 36px;
        left: 0px;
        display: none;
    }

    ul.view-dropdown {
        width: 200px;
    }

    ul.dropdown li,
    ul.view-dropdown li {
        padding: 0;
        margin-bottom: 5px;
        display: block;
    }

    ul.dropdown li:last-of-type,
    ul.view-dropdown li:last-of-type {
        margin-bottom: 0;
    }

    ul.dropdown li:hover,
    ul.view-dropdown li:hover {
        background: #D3D3D3;
        color: #fff;
    }

    ul.dropdown li i,
    ul.view-dropdown li i {
        margin-right: 5px;
    }

    .form-group {
        outline: none;
        font-size: 14px;
    }

    .form-btn {
        background: #FFA500;
        outline: none;
        border: none;
        padding: 4px 10px;
        color: #fff;
        font-size: 14px;
    }

    .left-top {
        padding: 10px;
    }

    .left-top input[type="text"] {
        width: 60px;
    }

    /*  main body css   */
    .left-body,
    .left-top {
        border: 1px solid #d9d9d9;
    }

    .side-pannel {
        background-color: #e7e7e7;
        width: 100px;
        padding: 10px;
    }

    .side-pannel input {
        margin-right: 5px;
    }

    .pannel-body {
        width: calc(100% - 100px);
    }
    .tooltip{
        position: absolute;
    top: 65%;
    right: -77px;
    background: #F9F9F9;
    color: #8D8D8D;
    padding: 3px 3px;
    border-radius: 5px;
    display: none;
    font-size: 13px;
    z-index:999;
    }
    .icon-container:hover .tooltip{
        display:block;
    }
  </style>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"
            integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw=="
            crossorigin="anonymous" referrerpolicy="no-referrer">
        </script>

<script>
    const BASE_URL = "http://localhost:5000";
    
    $(document).ready(function ( ) {
        // Function to handle tab clicks
        $('.tab-head li').click(function () {
            var tabId = $(this).attr('data-id');
            $('#' + tabId).show().siblings().hide();
            $(this).addClass('active').siblings().removeClass('active');

           
            localStorage.setItem('activeTab', tabId);
        });

        
        var activeTabId = localStorage.getItem('activeTab');
        if (activeTabId) {
            $('#' + activeTabId).show().siblings().hide();
            $('[data-id="' + activeTabId + '"]').addClass('active').siblings().removeClass('active');
        }

       
        $('.user-view-dropdown').click(function () {
            var $dropdown = $("#user-dropdown");
            $('.view-dropdown').not($dropdown).hide(); 
            $dropdown.toggle();
        });

        // Dropdown toggle functionality for View
        $('.open-view-menu').click(function () {
            var $dropdown = $("#view-dropdown");
            $('.view-dropdown').not($dropdown).hide(); 
            $dropdown.toggle();
        });

        // Dropdown toggle functionality for Report
        $('.open-report-menu').click(function () {
            var $dropdown = $("#report-dropdown");
            $('.view-dropdown').not($dropdown).hide(); 
            $dropdown.toggle();
        });

        $('.open-tools-menu').click(function () {
            var $dropdown = $("#tools-dropdown");
            $('.view-dropdown').not($dropdown).hide(); 
            $dropdown.toggle();
        });

        // Dropdown toggle functionality for File
        $('.open-file-menu').click(function () {
            var $dropdown = $("#file-dropdown");
            $("#user_name_id").val("{{request.user.user_name}}");
            $('.view-dropdown').not($dropdown).hide(); 
            $dropdown.toggle();
        });

        $('.closeBtn').click(function () {
            $(".trades-side").hide();
            $(".trades-body").css("width", "100% - 30px");
        });

        $('#closeChangePass').click(function () {
            $(".change-pass").hide();
        });
    });

    const changePasswordOpen = () =>  {
        console.log()
        $("#changepass").css("display", "block");
        $('.action_dropdown').hide();
    }



   
</script>
<script>
    $(document).ready(function() {
        // Function to handle tab clicks
        $('.tab-head li').click(function() {
            var tabId = $(this).attr('data-id');
            $('#' + tabId).show().siblings().hide();
            $(this).addClass('active').siblings().removeClass('active');
    
            // Store the active tab in local storage
            localStorage.setItem('activeTab', tabId);
        });
    
        // Function to show the stored active tab on page load
        var activeTabId = localStorage.getItem('activeTab');
        if (activeTabId) {
            $('#' + activeTabId).show().siblings().hide();
            $('[data-id="' + activeTabId + '"]').addClass('active').siblings().removeClass('active');
        }
    
        // Other dropdown toggle functionality...
        // ...
    });
    </script>

 
</html>