App/urls.py
from django.urls import path
from App.views import *
urlpatterns = [
    path("login/",LoginApi.as_view(),name="login"),
    path("logout/",LogoutUserAPIView.as_view(),name="logout"),
    path("add-user/",AddUserAPIView.as_view(),name="add-user"),
    path("edit-user/",EditUserApi.as_view(),name="edit-user"),
    path('update-password/', ResetPasswordView.as_view(), name='change-password'),
    path('user-profile/', UserProfileAPIView.as_view(), name='user-profile'),
    path('market-coin/', MaketWatchScreenApi.as_view(), name='add-market-coin'),
    path('buy-sell-coin/', BuySellSellApi.as_view(), name='buy-sell-coin'),
    path('trade-history/', TradeHistoryApi.as_view(), name='trade-history'),
    path('user-coin-list/', CoinNameApi.as_view(), name='user-coin-list'),
    path('user-list/', UserListApiView.as_view(), name='user-list'),
    path("position/", PositionManager.as_view(), name="position"),
    path("position-view/", OpenPositionView.as_view(), name="position-view"),
    path("account-summary/", AccountSummaryApi.as_view(), name="account-summary"),
    path("position-coins/", PositionCoinsManager.as_view(), name="position-coins"),
    path("trade-particular-view/<str:id>", TradeParticularViewApi.as_view(), name="trade-particular-view/"),
    path("permission-toggle/", MyUserPerissionToggle.as_view(), name="permission-toggle"),
    path("change-passwordweb-api/", ChangePasswordWebAPI.as_view(), name="change-passwordweb-api"),
    path("get-admin-api/", GetAllAdminApiView.as_view(), name="get-admin-api"),
    path("get-master-api/", GetMasterApiView.as_view(), name="get-master-api"),
    path("limit-user-creation/", LimitUserCreation.as_view(), name="limit-user-creation"),
    path("admin-right/", AdminRightApi.as_view(), name="admin-right"),
    path("admin-right-get/", AdminRigthsGetApi.as_view(), name="admin-right-get"),
    path("admin-trade-right/", MarketTradeRight.as_view(), name="admin-trade-right"),
    path("admin-trade-get/", MarketTradeGetApi.as_view(), name="admin-trade-get"),
    path("brk/", BrkApi.as_view(), name="brk"),
    path("table-chart/", TableChartAPi.as_view(), name="table-chart"),
    path("pie-chart-api/", PieChartHandlerApi.as_view(), name="pie-chart-api"),
    path("child-user-api/", ChildUserFetchAPI.as_view(), name="child-user-api"),
    path("get-client-api/", GetAllClient.as_view(), name="get-client-api"),
    path("login-history/", LoginHistoryApi.as_view(), name="login-history"),
    # path("user-list/", UserListApi.as_view(), name="user-list"),
    path("search-user-api/", SearchUserAPI.as_view(), name="search-user-api"),
    path("script-quantity-api/", ScriptQuantityAPI.as_view(), name="script-quantity-api"),
    path("settlement-api/", SettlementReportApi.as_view(), name="settlement-api"),
    path("web-script-quantity-api/", WebScriptQuantityAPI.as_view(), name="web-script-quantity-api"),
    path("position-header-api/", PositionTopHeader.as_view(), name="position-header-api"),
    path("account-summary-credit-api/", AccountSummaryCreditAPI.as_view(), name="account-summary-credit-api"),
    path("master-child-api/", MasterChildApi.as_view(), name="master-child-api"),
    
    path("account-limit/", AccountLimitApi.as_view(), name="account-limit"),
    path("user-details-api/", UserDetailsAPIView.as_view(), name="user-details-api"),
    path("quantity-setting-api/", QuanityUpdateAllApi.as_view(), name="quantity-setting-api"),
    path("brk-setting-api/", BrokrageSettings.as_view(), name="brk-setting-api"),
    path("trademargin-setting-api/", TradeMarginSetting.as_view(), name="trademargin-setting-api"),
    path("trademargin-all-setting-api/", TradeMarginUpdateAllApi.as_view(), name="trademargin-all-setting-api"),
    path("intraday-squareoff-check/", IntradaySquareoffCheck.as_view(), name="intraday-squareoff-check"),
    path("weekly-admin-api/", WeeklyAdminListApi.as_view(), name="weekly-admin-api"),
    path("user-script-position-track/", UserScriptPositionTrack.as_view(), name="user-script-position-track"),
    path("delete-indentifer/", DeleteIndentifer.as_view(), name="delete-indentifer"),
    path("credit-submit/", CreditSubmitHandler.as_view(), name="credit-submit"),
    path("message-latest/", MessageGetLatest.as_view(), name="message-latest"),
    path("userbrkandprofitloss-handle/", UserBrkAndProfitLossAPI.as_view(), name="userbrkandprofitloss-handle"),
]

Web/urls.py
from django.contrib import admin
from django.urls import path, include
from Web.views import *

urlpatterns = [
    path("",LoginView.as_view(),name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("first-login", FirstLogin.as_view(), name="first-login"),
    path("change-password",ChangePasswordView.as_view(),name="change-password"),
    path("dashboard",Dashboard.as_view(),name="dashboard"),
    
    
    path("add-user",AddUserView.as_view(),name="add-user"),
    path("list-user",ListUserView.as_view(),name="list-user"),
    path("edit-user/<str:id>",EditUserView.as_view(),name="edit-user"),
    # path("account-limit",AccountLimitView.as_view(),name="account-limit"),
    
    
    path("download-csv",DownloadCSVView.as_view(),name="download-csv"),
    path("search-user",SearchUserView.as_view(),name="search-user"),
    path("search-all-user",SearchUsersView.as_view(),name="search-all-user"),
    
    
    path("user-deatils",UserDeatilsView.as_view(),name="user-deatils"),
    path("user-deatils-by-id/<str:id>",UserDeatilsViewById.as_view(),name="user-deatils-by-id"),
    path("tab-open-position/",OpenPositionView.as_view(),name="tab-open-position"),
    path("user-script/<str:id>",UserScriptMaster.as_view(),name="user-script"),
    
    path("group-setting",GropuSettingView.as_view(),name="group-setting"),
    path("script-quantity-setting",ScriptQuantitySetting.as_view(),name="script-quantity-setting"),
    path("tab-trade/<str:id>",TabTrades.as_view(),name="tab-trade"),
    
    
    path("quantity-setting/<str:id>",QuantitySettingView.as_view(),name="quantity-setting"),
    path("brk/<str:id>",BrkView.as_view(),name="brk"),
    path("trade-margin/<str:id>",TradeMarginTab.as_view(),name="trade-margin"),
    path("credit/<str:id>",CreditView.as_view(),name="credit"),
    path("tab-account-summary/<str:id>",TabAccountSummary.as_view(),name="tab-account-summary"),
    path("tab-settlement/<str:id>",TabSettlement.as_view(),name="tab-settlement"),
    path("rejection-log/<str:id>", RejectionLogView.as_view(), name="rejection-log"),
    path("share-deatils",ShareDetailsView.as_view(),name="share-deatils"),
    path("user-info/<str:id>",UserInfoView.as_view(),name="user-info"),
    
    
    path("market-watch",MarketWatchView.as_view(),name="market-watch"),
    path("sybols-watch",SybolsView.as_view(),name="sybols-watch"),
    path("trades",TradesView.as_view(),name="trades"),
    path("orders",OrdersView.as_view(),name="orders"),
    path("positions",PositionsView.as_view(),name="positions"),
    path("profit-and-loss",ProfitAndLoss.as_view(),name="profit-and-loss"),
    path("m2m-profit-and-loss",M2MProfitAndLoss.as_view(),name="m2m-profit-and-loss"),
    path("intraday-history",IntradayHistory.as_view(),name="intraday-history"),
    path("rejection-log",RejectionLogTab.as_view(),name="rejection-log"),
    path("login-history",LoginHistory.as_view(),name="login-history"),
    
    
    path("open-position",OpenPosition.as_view(),name="open-position"),
    path("manage-trades",ManageTrades.as_view(),name="manage-trades"),
    path("trade-account",TradeAccount.as_view(),name="trade-account"),
    path("settlement",SettlementView.as_view(),name="settlement"),
    path("account-summary",AccountSummary.as_view(),name="account-summary"),
    path("bill-generate",BillGenerate.as_view(),name="bill-generate"),
    path("trades-margins",TradeMargin.as_view(),name="trades-margins"),
    path("script-master",ScriptMaster.as_view(),name="script-master"),
    path("logs-history",LogsHistory.as_view(),name="logs-history"),
    path("user-logs-new",UserLogsNew.as_view(),name="user-logs-new"),
    path("user-script-position-track",UserScriptPositionTrack.as_view(),name="user-script-position-track"),
    path("position-track-view-orders",PositionTrackViewOrders.as_view(),name="position-track-view-orders"),
    path("user-script-position-trac-pl",UserScriptPositionTrackPl.as_view(),name="user-script-position-trac-pl"),
    path("script-quantity",ScriptQuantity.as_view(),name="script-quantity"),
    path("weekly-admin",WeeklyAdminView.as_view(),name="weekly-admin"),
    
    
    
    path("exchange-time",ExchangeTimeSchedule.as_view(),name="exchange-time"),
    path("message",MassageView.as_view(),name="message"),
    
    
#----------------------csv download ---------------------#

    path('rejection-csv/<str:id>/', RejectionDownloadCSVView.as_view(), name='rejection-csv'),
    path('trade-csv/<str:id>/', TradeDownloadCsv.as_view(), name='trade-csv'),
    path('credit-csv/<str:id>/', CreditDownloadCSVView.as_view(), name='credit-csv'),
    path('account-summary-tab-csv/<str:id>/', AccountSummaryTabDownloadCSV.as_view(), name='account-summary-tab-csv'),
    path('account-summary-csv/<str:id>/', AccountSummaryDownloadCSV.as_view(), name='account-summary-csv'),
    path('manage-trades-csv/', TradesDownloadCSVView.as_view(), name='manage-trades-csv'),
    path('view-trades-csv/', ViewTradesDownloadCSV.as_view(), name='view-trades-csv'),
    path('order-csv-download/', OrderDownloadCSVView.as_view(), name='order-csv-download'),
    path('open-position-view/', OpenPositionView.as_view(), name='open-position-view'),

]

quickTradeBackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include("App.urls")),
    path("",include(("Web.urls", "Admin"), namespace="Admin")),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/User/list-user.html
{% extends "index.html" %} {% block content %}
<style>
    
  
    .new-table {
        width: calc(100% - 240px);
    }
    
        .switch {
          position: relative;
          display: inline-block;
          display: inline-block;
          width: 42px;
          height: 20px;
          top: 2px;
        }
        
        .switch input { 
          opacity: 0;
          width: 0;
          height: 0;
          box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px;
        }
        
        .slider {
          position: absolute;
          cursor: pointer;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background-color: #ccc;
          -webkit-transition: .4s;
          transition: .4s;
        }
        
        .slider:before {
          position: absolute;
          content: "";
          height: 20px;
          width: 20px;
          left: 0px;
          bottom: 0px;
          background-color: white;
          -webkit-transition: .4s;
          transition: .4s;
        }
        
        input:checked + .slider {
          background-color: #2196F3;
        }
        
        input:focus + .slider {
          box-shadow: 0 0 1px #2196F3;
        }
        
        input:checked + .slider:before {
          -webkit-transform: translateX(21px);
          -ms-transform: translateX(21px);
          transform: translateX(21px);
        }
        
        /* Rounded sliders */
        .slider.round {
          border-radius: 34px;
        }
        
        .slider.round:before {
          border-radius: 50%;
        }
        .pos-relate{
            position: relative;
        }
        .dropdown_action{
            cursor: pointer;
        }
        .action_dropdown {
            position: absolute;
            background: #fff;
            z-index: 99;
            top: 47px;
            left: 49px;
            width: 200px;
            box-shadow: 0px 0px 5px #d9d9d9;
            display: none;
            text-align: center;
            border: solid;
            border-width: 1px;
        }
        .action_dropdown li{
            display:block;
            cursor: pointer;

        }
        .action_dropdown li:hover{
            background: skyblue;
            border-radius: 5px;
        }
        .popupClass{
            position:absolute;
        }
        .user-cell:hover{
            cursor: pointer;
            color: blue;
        }
</style>

<div class="tab-content" id="user-list">
    <div class="flex">
        <div class="trade-download">
            <div style="transform: rotate(90deg);padding-left: 10px; cursor:pointer;">
                <p id="listUserFilterId">Filter</p>
            </div>
            <span>
                <a href="{% url 'Admin:download-csv' %}"><i class="fa-solid fa-file-csv"></i></a>
            </span>
        </div>
        <div class="trades-side" style="width: 200px">
            <div class="trade-top">
                <div class="flex space-bw">
                    <div>
                        <p>Filter</p>
                    </div>
                    <div class="closeBtn">
                        <i class="fa-solid fa-xmark"></i>
                    </div>
                </div>
            </div>
            <form method="get">
                {% csrf_token %}
                <div class="trade-btm">
                    <div>
                        <label for="">Filter Type:</label>
                        <select name="user_name">
                            <option value="">All</option>
                            {% for i in user_list  %}
                                <option value="{{ i }}">{{ i }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div>
                        <label for="">User Type:</label>
                        <select name="user_type" >
                            <option value="">All</option>
                            <option value="Client">Client</option>
                            <option value="Master">Master</option>
                        </select>
                    </div>
                    <div>
                    <label for="coin_name">User Status:</label>
                    <select name="user_status" >
                        <option value="">All</option>
                        <option value="Active">Active</option>
                        <option value="In Active">In Active</option>
                    </select>

                    </div>
                    <div>
                        <label for=""></label>
                        <button type="submit" class="form-btn">Search</button>
                        <a style="color:#fff !important; padding: 2px;" href="{% url 'Admin:list-user' %}" value="Clear" class="cancel-btn">Clear</a>
                    </div>
                </div>
            </form>
        </div>
        <div class="user-table new-table">
            {% if client %}
            <table style="width: 100%;">
                
                <tr>
                    <th>Edit</th>
                    <th>Action</th>
                    <th>Username</th>
                    <th>Name</th>   
                    <th>Type</th>
                    <th>Parent</th>
                    <th>Credit</th>
                    <th>Balance</th>
                    <th>Sharing%</th>
                    <th>Bet</th>
                    <th>Close Only</th>
                    <th>Margin Sq..</th>
                    <th>Status</th>
                    <th>Created Date</th>
                    <th>Ip Address</th>
                    <th>Last Login</th>
                </tr>
                <div class="pos-relate">
                    <ul class="action_dropdown" id="actionDropDown">
                        <li><a onClick="changePasswordOpen()">Change Password</a></li>
                        {% comment %} <li><a href="#">Share Details</a></li> {% endcomment %}
                        <li><a id="accountLimitId" onClick="accountLimit()">Account Limit</a></li>
                        {% if request.user.user_type == "Admin" or request.user.user_type == "SuperAdmin" %}
                            <li><a onClick="adminRights()" id="adminRightuserId">Admin Rights</a></li>
                        {% else %}
                        <li><a onClick="adminRights()" id="adminRightuserId">Master Rights</a></li>
                        {% endif %}
                        <li><a onClick="tradeRights()" id="marketTradeRightBtnId">Market Trade Right</a></li>
                        <li><a onClick="intradaySquare()" id="intradaySquareBtnId">Indraday Square Off</a></li>
                    </ul>
                </div>
           {% for i in client %}
                <tr>
                    <td>
                        <ul>
                            <li>
                                <a href="{% url 'Admin:edit-user' i.id %}">
                                    <i class="fa-solid fa-pen"></i>
                                </a>
                            </li>
                        </ul>
                    </td>
                    <td class="pos-relate"> 
                        <ul class="dropdown_action">
                            <li>
                                <i class="fa-solid fa-ellipsis" onClick="clickActionBtn(event)" data-hidden-value="{{i.user_name}}__abc__{{i.id}}"></i>  
                            </li>
                        </ul>
                    </td>
                    <td style="text-decoration: underline;" class="user-cell" onClick='particularUserView("{{i.id}}")'>{{i.user_name}}</td>
                    <td>{{i.full_name}}</td>
                    <td>{{i.user_type}}</td>
                    <td>{{i.parent}}</td>
                    <td>{{i.credit}}</td>
                    <td>{{i.balance}}</td>
                    <td>00.0</td>
                    {% if i.user_type == "Master" or i.user_type == "Client" %}
                    <td>
                        <label class="switch">
                            <input onClick="callToggleApi('{{i.id}}', `bet`)" type="checkbox" {% if i.bet %} checked {% endif %}>
                            <span class="slider round"></span>
                        </label>
                    </td>
                    <td>
                        <label class="switch">
                            <input onClick="callToggleApi('{{i.id}}', `close_only`)" type="checkbox" {% if i.close_only %} checked {% endif %}>
                            <span class="slider round"></span>
                        </label>
                    </td>
                    <td>
                        <label class="switch">
                            <input onClick="callToggleApi('{{i.id}}', `margin_sq`)" type="checkbox" {% if i.margin_sq %} checked {% endif %}>
                            <span class="slider round"></span>
                        </label>
                    </td>
                    <td>
                        <label class="switch">
                            <input onClick="callToggleApi('{{i.id}}', `status`)" type="checkbox" {% if i.status %} checked {% endif %}>
                            <span class="slider round"></span>
                        </label>
                    </td>
                    {% else %}
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    {% endif %}
                    <td>{{i.created_at}}</td>
                        <td>{{ i.user_history.first.ip_address }}</td>
                    {% if i.last_login != None %}  
                        <td>{{i.last_login }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </table>
            {% else %}
            <div style="display: flex;justify-content: center;margin-top: 14%;">
              <p>No data found</p>
            </div>
        {% endif %}
        </div>
    </div>

    {% comment %} seleted user id {% endcomment %}
    <input hidden id="current_selected_userId"/>
</div>


<script>

    $('.closeBtn').click(function () {
        $(".trades-side").hide();
        $(".trades-body").css("width", "100%");
    });
    
    $('#listUserFilterId').click(function () {
      $(".trades-side").show();
      $(".trades-body").css("width", "69%");
    });
    


    $(document).on("click", function(event){
        var $trigger = $(".pos-relate");
        if($trigger !== event.target && !$trigger.has(event.target).length){
            $(".action_dropdown").hide();
        }
    });
 
    $('.dropdown_action').click(function(){
        $('.action_dropdown').toggle();
    })

    const clickActionBtn = (event) => {
        const result = event.target.dataset.hiddenValue?.split("__abc__");
        $("#user_name_id").val(result[0]);
        $("#current_selected_userId").val(result[result.length - 1]);
    }

    const callToggleApi = (id, key) => {
        $.ajax({
            type:'POST',
            url:'{% url "permission-toggle" %}',
            headers: {'X-CSRFToken': '{{ csrf_token }}'},
            data: {
                id,
                key
            }
        })
    }

    // please dont touch harish ====>
    //piyush bhai kuch nahi aata tuje cutiya salla  ====>
    const particularUserView = id => {
        var left = (screen.width/2)-(1200/2);
        var top = (screen.height/2)-(600/2);
        window.open(`user-deatils-by-id/${id}`, 'NewWindow', `width=1200,height=600,left=${left},top=${top}`);
        localStorage.setItem("currentUserID", id);
    }
    
    {% comment %} const userCells = document.querySelectorAll('.user-cell');
    const userTabOpen = (userName) => {
        window.open('user-deatils', 'NewWindow', 'width=1200,height=600');
    };
    userCells.forEach(cell => {
        cell.addEventListener('click', () => {
            const userName = cell.textContent;
            userTabOpen(userName);
        });
    }); {% endcomment %}
    
    
</script>


{% endblock content %}

templates/User/search-user.html
{% extends "index.html" %} {% block content %}

<div class="tab-content" id="search-user">
    <div class="user-table search-user">
        <div class="seach-area" style="margin-top:10px;">
            <label for="user-search-input">Search User:</label>
            <input type="search" id="user-search-input">
        </div>
        <div class="outcome-user">

            <ul id="searchUserUlId">
            </ul>
        </div>
    </div>
</div>
<style>
    .plus-sign {
        margin-right: 5px;
        padding: 1px 3px;
        border: 1px solid #808080;
        color: #3d3de9;
        background-color: #9c9696;
        display: inline-block;
        font-size: 10px;
        text-decoration: none;
    }
</style>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    const particularUserView = id => {
        var left = (screen.width/2)-(1200/2);
        var top = (screen.height/2)-(600/2);
        window.open(`user-deatils-by-id/${id}`, 'NewWindow', `width=1200,height=600,left=${left},top=${top}`);
        localStorage.setItem("currentUserID", id);
    }

    const user_type = "{{request.user.user_type}}"
    $(document).ready(function () {
        function loadAllUsers() {
            $.ajax({
                url: '{% url 'search-user-api' %}',
                method: 'GET',
                success: function (data) {
                    if (user_type !== "SuperAdmin") {
                        data.data.map(mapItem =>
                            $("#searchUserUlId").append(`
                                <ul>
                                    <li style="list-style-type: none;">
                                        <a href="#" class="plus-sign">+</a> <a href="#" onclick="particularUserView('${mapItem?.master_user}')">${mapItem?.master_user_details?.user_name} (${mapItem?.master_user_details?.user_type})</a>
                                        <ul>
                                            ${mapItem?.clients?.map(child => `<li style="list-style-type: none;"><a href="#" onclick="particularUserView('${child?.client}')">${child?.client_user_details.user_name} (${child?.client_user_details?.user_type})</a></li>`).join('')}
                                        </ul>
                                    </li>
                                </ul>`)
                        );
                    } else {
                        data.data.map(mapItem =>
                            $("#searchUserUlId").append(`
                                <ul>
                                    <li style="list-style-type: none;">
                                        <a href="#" class="plus-sign">+</a> <a href="#" onclick="particularUserView('${mapItem.user}')">${mapItem.user_details.user_name} (${mapItem.user_details.user_type})</a>
                                        <ul>
                                            ${mapItem.masters.map(master => `<li style="list-style-type: none;"> <a href="#" class="plus-sign">+</a> <a href="#" onclick="particularUserView('${master.master_user}')">${master.master_user_details.user_name} (${master.master_user_details.user_type})</a>
                                                                            <ul>
                                                                                ${master.clients.map(child => `<li style="list-style-type: none;"><a href="#" onclick="particularUserView('${child.client}')">${child.client_user_details.user_name} (${child.client_user_details.user_type})</a></li>`).join('')}
                                                                            </ul></li>`)
                                            .join('')}
                                        </ul>
                                        <ul>
                                         ${mapItem.clients.map(child => `<li style="list-style-type: none;"><a href="#" onclick="particularUserView('${child.client}')">${child.client_user_details.user_name} (${child.client_user_details.user_type})</a></li>`).join('')}
                                        </ul>
                                    </li>
                                </ul>`)
                        );
                    }
                },
                error: function (error) {
                    console.log(error);
                }
            });
        }
        loadAllUsers();
    
        // Event delegation for click
        $('#searchUserUlId').on('click', 'li > a', function (e) {
            e.preventDefault();
            var li = $(this).parent('li');
            if (!li.has('ul')) {
                return;
            }
            li.children('ul').toggle();
        });
    });


    $('#user-search-input').on('input', function () {
        var searchTerm = $(this).val().toLowerCase();
        $('#searchUserUlId li').each(function () {
            var userText = $(this).text().toLowerCase();
            if (userText.indexOf(searchTerm) === -1) {
                $(this).hide();
            } else {
                $(this).show();
            }
        });
    });
    

</script>



{% endblock content %}