App/urls.py
from django.urls import path
from App.views import *
urlpatterns = [
    path("login/",LoginApi.as_view(),name="login"),
    path("logout/",LogoutUserAPIView.as_view(),name="logout"),
    path("add-user/",AddUserAPIView.as_view(),name="add-user"),
    path("edit-user/",EditUserApi.as_view(),name="edit-user"),
    path('update-password/', ResetPasswordView.as_view(), name='change-password'),
    path('user-profile/', UserProfileAPIView.as_view(), name='user-profile'),
    path('market-coin/', MaketWatchScreenApi.as_view(), name='add-market-coin'),
    path('buy-sell-coin/', BuySellSellApi.as_view(), name='buy-sell-coin'),
    path('trade-history/', TradeHistoryApi.as_view(), name='trade-history'),
    path('user-coin-list/', CoinNameApi.as_view(), name='user-coin-list'),
    path('user-list/', UserListApiView.as_view(), name='user-list'),
    path("position/", PositionManager.as_view(), name="position"),
    path("position-view/", OpenPositionView.as_view(), name="position-view"),
    path("account-summary/", AccountSummaryApi.as_view(), name="account-summary"),
    path("position-coins/", PositionCoinsManager.as_view(), name="position-coins"),
    path("trade-particular-view/<str:id>", TradeParticularViewApi.as_view(), name="trade-particular-view/"),
    path("permission-toggle/", MyUserPerissionToggle.as_view(), name="permission-toggle"),
    path("change-passwordweb-api/", ChangePasswordWebAPI.as_view(), name="change-passwordweb-api"),
    path("get-admin-api/", GetAllAdminApiView.as_view(), name="get-admin-api"),
    path("get-master-api/", GetMasterApiView.as_view(), name="get-master-api"),
    path("limit-user-creation/", LimitUserCreation.as_view(), name="limit-user-creation"),
    path("admin-right/", AdminRightApi.as_view(), name="admin-right"),
    path("admin-right-get/", AdminRigthsGetApi.as_view(), name="admin-right-get"),
    path("admin-trade-right/", MarketTradeRight.as_view(), name="admin-trade-right"),
    path("admin-trade-get/", MarketTradeGetApi.as_view(), name="admin-trade-get"),
    path("brk/", BrkApi.as_view(), name="brk"),
    path("table-chart/", TableChartAPi.as_view(), name="table-chart"),
    path("pie-chart-api/", PieChartHandlerApi.as_view(), name="pie-chart-api"),
    path("child-user-api/", ChildUserFetchAPI.as_view(), name="child-user-api"),
    path("get-client-api/", GetAllClient.as_view(), name="get-client-api"),
    path("login-history/", LoginHistoryApi.as_view(), name="login-history"),
    # path("user-list/", UserListApi.as_view(), name="user-list"),
    path("search-user-api/", SearchUserAPI.as_view(), name="search-user-api"),
    path("script-quantity-api/", ScriptQuantityAPI.as_view(), name="script-quantity-api"),
    path("settlement-api/", SettlementReportApi.as_view(), name="settlement-api"),
    path("web-script-quantity-api/", WebScriptQuantityAPI.as_view(), name="web-script-quantity-api"),
    path("position-header-api/", PositionTopHeader.as_view(), name="position-header-api"),
    path("account-summary-credit-api/", AccountSummaryCreditAPI.as_view(), name="account-summary-credit-api"),
    path("master-child-api/", MasterChildApi.as_view(), name="master-child-api"),
    
    path("account-limit/", AccountLimitApi.as_view(), name="account-limit"),
    path("user-details-api/", UserDetailsAPIView.as_view(), name="user-details-api"),
    path("quantity-setting-api/", QuanityUpdateAllApi.as_view(), name="quantity-setting-api"),
    path("brk-setting-api/", BrokrageSettings.as_view(), name="brk-setting-api"),
    path("trademargin-setting-api/", TradeMarginSetting.as_view(), name="trademargin-setting-api"),
    path("trademargin-all-setting-api/", TradeMarginUpdateAllApi.as_view(), name="trademargin-all-setting-api"),
    path("intraday-squareoff-check/", IntradaySquareoffCheck.as_view(), name="intraday-squareoff-check"),
    path("weekly-admin-api/", WeeklyAdminListApi.as_view(), name="weekly-admin-api"),
    path("user-script-position-track/", UserScriptPositionTrack.as_view(), name="user-script-position-track"),
    path("delete-indentifer/", DeleteIndentifer.as_view(), name="delete-indentifer"),
    path("credit-submit/", CreditSubmitHandler.as_view(), name="credit-submit"),
    path("message-latest/", MessageGetLatest.as_view(), name="message-latest"),
    path("userbrkandprofitloss-handle/", UserBrkAndProfitLossAPI.as_view(), name="userbrkandprofitloss-handle"),
]

Web/urls.py
from django.contrib import admin
from django.urls import path, include
from Web.views import *

urlpatterns = [
    path("",LoginView.as_view(),name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("first-login", FirstLogin.as_view(), name="first-login"),
    path("change-password",ChangePasswordView.as_view(),name="change-password"),
    path("dashboard",Dashboard.as_view(),name="dashboard"),
    
    
    path("add-user",AddUserView.as_view(),name="add-user"),
    path("list-user",ListUserView.as_view(),name="list-user"),
    path("edit-user/<str:id>",EditUserView.as_view(),name="edit-user"),
    # path("account-limit",AccountLimitView.as_view(),name="account-limit"),
    
    
    path("download-csv",DownloadCSVView.as_view(),name="download-csv"),
    path("search-user",SearchUserView.as_view(),name="search-user"),
    path("search-all-user",SearchUsersView.as_view(),name="search-all-user"),
    
    
    path("user-deatils",UserDeatilsView.as_view(),name="user-deatils"),
    path("user-deatils-by-id/<str:id>",UserDeatilsViewById.as_view(),name="user-deatils-by-id"),
    path("tab-open-position/",OpenPositionView.as_view(),name="tab-open-position"),
    path("user-script/<str:id>",UserScriptMaster.as_view(),name="user-script"),
    
    path("group-setting",GropuSettingView.as_view(),name="group-setting"),
    path("script-quantity-setting",ScriptQuantitySetting.as_view(),name="script-quantity-setting"),
    path("tab-trade/<str:id>",TabTrades.as_view(),name="tab-trade"),
    
    
    path("quantity-setting/<str:id>",QuantitySettingView.as_view(),name="quantity-setting"),
    path("brk/<str:id>",BrkView.as_view(),name="brk"),
    path("trade-margin/<str:id>",TradeMarginTab.as_view(),name="trade-margin"),
    path("credit/<str:id>",CreditView.as_view(),name="credit"),
    path("tab-account-summary/<str:id>",TabAccountSummary.as_view(),name="tab-account-summary"),
    path("tab-settlement/<str:id>",TabSettlement.as_view(),name="tab-settlement"),
    path("rejection-log/<str:id>", RejectionLogView.as_view(), name="rejection-log"),
    path("share-deatils",ShareDetailsView.as_view(),name="share-deatils"),
    path("user-info/<str:id>",UserInfoView.as_view(),name="user-info"),
    
    
    path("market-watch",MarketWatchView.as_view(),name="market-watch"),
    path("sybols-watch",SybolsView.as_view(),name="sybols-watch"),
    path("trades",TradesView.as_view(),name="trades"),
    path("orders",OrdersView.as_view(),name="orders"),
    path("positions",PositionsView.as_view(),name="positions"),
    path("profit-and-loss",ProfitAndLoss.as_view(),name="profit-and-loss"),
    path("m2m-profit-and-loss",M2MProfitAndLoss.as_view(),name="m2m-profit-and-loss"),
    path("intraday-history",IntradayHistory.as_view(),name="intraday-history"),
    path("rejection-log",RejectionLogTab.as_view(),name="rejection-log"),
    path("login-history",LoginHistory.as_view(),name="login-history"),
    
    
    path("open-position",OpenPosition.as_view(),name="open-position"),
    path("manage-trades",ManageTrades.as_view(),name="manage-trades"),
    path("trade-account",TradeAccount.as_view(),name="trade-account"),
    path("settlement",SettlementView.as_view(),name="settlement"),
    path("account-summary",AccountSummary.as_view(),name="account-summary"),
    path("bill-generate",BillGenerate.as_view(),name="bill-generate"),
    path("trades-margins",TradeMargin.as_view(),name="trades-margins"),
    path("script-master",ScriptMaster.as_view(),name="script-master"),
    path("logs-history",LogsHistory.as_view(),name="logs-history"),
    path("user-logs-new",UserLogsNew.as_view(),name="user-logs-new"),
    path("user-script-position-track",UserScriptPositionTrack.as_view(),name="user-script-position-track"),
    path("position-track-view-orders",PositionTrackViewOrders.as_view(),name="position-track-view-orders"),
    path("user-script-position-trac-pl",UserScriptPositionTrackPl.as_view(),name="user-script-position-trac-pl"),
    path("script-quantity",ScriptQuantity.as_view(),name="script-quantity"),
    path("weekly-admin",WeeklyAdminView.as_view(),name="weekly-admin"),
    
    
    
    path("exchange-time",ExchangeTimeSchedule.as_view(),name="exchange-time"),
    path("message",MassageView.as_view(),name="message"),
    
    
#----------------------csv download ---------------------#

    path('rejection-csv/<str:id>/', RejectionDownloadCSVView.as_view(), name='rejection-csv'),
    path('trade-csv/<str:id>/', TradeDownloadCsv.as_view(), name='trade-csv'),
    path('credit-csv/<str:id>/', CreditDownloadCSVView.as_view(), name='credit-csv'),
    path('account-summary-tab-csv/<str:id>/', AccountSummaryTabDownloadCSV.as_view(), name='account-summary-tab-csv'),
    path('account-summary-csv/<str:id>/', AccountSummaryDownloadCSV.as_view(), name='account-summary-csv'),
    path('manage-trades-csv/', TradesDownloadCSVView.as_view(), name='manage-trades-csv'),
    path('view-trades-csv/', ViewTradesDownloadCSV.as_view(), name='view-trades-csv'),
    path('order-csv-download/', OrderDownloadCSVView.as_view(), name='order-csv-download'),
    path('open-position-view/', OpenPositionView.as_view(), name='open-position-view'),

]

quickTradeBackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include("App.urls")),
    path("",include(("Web.urls", "Admin"), namespace="Admin")),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/report/account-summary.html
{% extends "index.html" %} {% block content %}


<div class="tab-content" id="accountsummary">
    <div class="flex">
        <div class="trade-download">
            <div style="transform: rotate(90deg);padding-left: 10px; cursor:pointer;">
                <p id="accountFilterId">Filter</p>
            </div>
            <span>
                <a href="{% url 'Admin:account-summary-csv' id %}"><i class="fa-solid fa-file-csv"></i></a>
            </span>
        </div>
        <div class="trades-side">
            <div class="trade-top">
                <div class="flex space-bw">
                    <div>
                        <p>Filter</p>
                    </div>
                    <div class="closeBtn">
                        <i class="fa-solid fa-xmark"></i>
                    </div>
                </div>
            </div>
            <form method="get">
                {% csrf_token %}
                <div class="trade-btm">
                    <div>
                        <label for="">From:</label>
                        <input type="date" name="from_date" >
                    </div>
                    <div>
                        <label for="">To:</label>
                        <input type="date" name="to_date" >
                    </div>
                    <div>
                        <label for="">Username:</label>
                        <select  >
                            <option value="">{{request.user.user_name}}</option>
                        </select>
                    </div>
                    <div class="flex">
                        <div class="mr flex">
                            <p style="font-size: 14px; margin-right: 5px;">P/L</p>
                            <input type="checkbox" name="p_and_l" id="ppandlID" class="unset mb-0">
                        </div>
                        <div class="mr flex">
                            <p style="font-size: 14px; margin-right: 5px;">Brk</p>
                            <input type="checkbox" name="brk" id="bbrkId" class="unset mb-0">
                        </div>
                        <div class="mr flex">
                            <p style="font-size: 14px; margin-right: 5px;">Credit</p>
                            <input type="checkbox" name="credit" id="creditCheckBoxIds" class="unset mb-0">
                        </div>
                    </div>
                    <div>
                        <label for=""></label>
                        <button type="submit" value="View" class="form-btn">View</button>
                        <a style="color: #fff !important; padding: 2px;" href="{% url 'Admin:account-summary' %}" class="cancel-btn">Clear</a>
                    </div>
                </div>
            </form>
        </div>
        <div class="trades-body user-table" style="margin-top:1%;">
            {% comment %} <button class="delete-btn">Delete</button> {% endcomment %}
            {% if account_summary %}
            <table style="width: 100%;">
                <tr>
                    <th>Date</th>
                    <th>Username</th>
                    <th>Particular</th>
                    <th>Qty</th>
                    <th>Buy/Sell</th>
                    <th>Price</th>
                    <th>Average Price</th>
                    <th>Type</th>
                    <th>Amount</th>
                    <th>Closing</th>
                    <th>Open Qty</th>
                </tr>
                {% for i in account_summary %}
                <tr>
                    <td>{{i.created_at}}</td>
                    <td>{{i.user_summary__user_name}}</td>
                    <td>{{i.particular}}</td>
                    <td>{{i.quantity}}</td>
                    {% if i.buy_sell_type == "BUY" %}
                    <td style="color: blue;">{{i.buy_sell_type}}</td>
                    {% else %}
                    <td style="color: red;">{{i.buy_sell_type}}</td>
                    {% endif %}
                    <td>{{i.price}}</td>
                    <td>{{i.average|floatformat:2}}</td>
                    <td>{{i.summary_flg}}</td>
                    {% if i.amount > 0 %}
                        <td style="color: blue;">{{i.amount|floatformat:2}}</td>
                    {% else %}
                        <td style="color: red;">{{i.amount|floatformat:2}}</td>
                    {% endif %}
                    <td>{{i.closing}}</td>
                    <td>{{i.open_qty}}</td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
            <div style="display: flex;justify-content: center;margin-top: 14%;">
              <p>No data found</p>
            </div>
        {% endif %}
        </div>
    </div>
</div>

<script>

    $(document).ready(function() {
        $('#ppandlID, #bbrkId').change(function() {
          if ($(this).is(':checked')) {
            $('#creditCheckBoxIds').prop('checked', false);
          }
        });
        $('#creditCheckBoxIds').change(function() {
          if ($(this).is(':checked')) {
            $('#ppandlID, #bbrkId').prop('checked', false);
          }
        });
      });


    $('.closeBtn').click(function () {
        $(".trades-side").hide();
        $(".trades-body").css("width", "95%");
    });
    
    $('#accountFilterId').click(function () {
        $(".trades-side").show();
        $(".trades-body").css("width", "79%");
    });
  </script>

{% endblock content %}

templates/report/bill-generate.html
{% extends "index.html" %} {% block content %}

<div class="tab-content" id="billgenerate">
    <div class="flex">
        <div class="trade-download">
            <div style="transform: rotate(90deg);padding-left: 10px;">
                <p>Filter</p>
            </div>
            <span>
                <a href=""><i class="fa-solid fa-file-csv"></i></a>
            </span>
        </div>
        <div class="trades-side">
            <div class="trade-top">
                <div class="flex space-bw">
                    <div>
                        <p>Filter</p>
                    </div>
                    <div class="closeBtn">
                        <i class="fa-solid fa-xmark"></i>
                    </div>
                </div>
            </div>
            <div class="trade-btm">
                <div>
                    <label for="">From:</label>
                    <input type="date"  >
                </div>
                <div>
                    <label for="">To:</label>
                    <input type="date"  >
                </div>
                <div>
                    <label for="">Username:</label>
                    <select  >
                        <option value="">DEM999</option>
                    </select>
                </div>
                <div>
                    <label for="">Select:</label>
                    <select  >
                        <option value="">PDF</option>
                        <option value="">Excel</option>
                    </select>
                </div>
                <div>
                    <label for="">PDF Type:</label>
                    <select  >
                        <option value="">Regular Report</option>
                        <option value="">Advance Report</option>
                    </select>
                </div>
                <div>
                    <label for=""></label>
                    <input type="submit" value="View" class="form-btn">
                    <input type="submit" value="Clear" class="cancel-btn">
                </div>
            </div>
        </div>
        <!-- <div class="trades-body user-table">
            <button class="delete-btn">Delete</button>
            <table style="width: 100%;">
                <tr>
                    <th>Username</th>
                    <th>Symbol</th>
                    <th>Type</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Brk</th>
                    <th>Deal</th>
                    <th>Status</th>
                    <th>Order Time</th>
                    <th>Execution Time</th>
                    <th>IPAddress</th>
                    <th>DeviceId</th>
                    <th>Reference Price</th>
                    <th>Order Method</th>
                </tr>
                <tr>
                    <td>Username</td>
                    <td>Symbol</td>
                    <td>Type</td>
                    <td>Quantity</td>
                    <td>Price</td>
                    <td>Brk</td>
                    <td>Deal</td>
                    <td>Status</td>
                    <td>Order Time</td>
                    <td>Execution Time</td>
                    <td>IPAddress</td>
                    <td>DeviceId</td>
                    <td>Reference Price</td>
                    <td>Order Method</td>
                </tr>
            </table>
        </div> -->
    </div>
</div>

{% endblock content %}

templates/report/manage-trades.html
{% extends "index.html" %} {% block content %}


<div class="tab-content" id="managetrades">
    <div class="flex">
        <div class="trade-download">
            <div style="transform: rotate(90deg);padding-left: 10px;cursor:pointer;">
                <p id="manageTradesFilterId">Filter</p>
            </div>
            <span>
                <a href="{% url 'Admin:manage-trades-csv' %}?from_date={{ from_date }}&to_date={{ to_date }}&exchange={{ exchange }}&symbol={{ symbol }}&download_csv=true" class="download-csv-link">
                    <i class="fa-solid fa-file-csv"></i>
                  </a>
            </span>
        </div>
        <div class="trades-side">
            <div class="trade-top">
                <div class="flex space-bw">
                    <div>
                        <p>Filter</p>
                    </div>
                    <div class="closeBtn">
                        <i class="fa-solid fa-xmark"></i>
                    </div>
                </div>
            </div>
            <form method="get">
                {% csrf_token %}
                <div class="trade-btm">
                    <div>
                        <label for="">From:</label>
                        <input type="date" name="from_date" >
                    </div>
                    <div>
                        <label for="">To:</label>
                        <input type="date" name="to_date" >
                    </div>
                    <div>
                        <label for="">Username:</label>
                        <select name="user_name" >
                            <option value="">All</option>
                            {% for i in user %}
                                <option value="{{ i.user_name }}">{{ i.user_name }}</option>
                            {% endfor %}
                        </select>
                        
                    </div>
                    <div>
                        <label for="">Status:</label>
                        <select name="status" >
                            <option value="">All</option>
                            <option value="">Successful</option>
                            <option value="Pending">Pending</option>
                        </select>
                    </div>
                    <div>
                        <label for="">Exchange:</label>
                        <select name="exchange" >
                            <option value="">Select</option>
                            {% for i in symbol_name %}
                            <option value="{{i.symbol_name}}">{{i.symbol_name}}</option>
                          {% endfor %}
                        </select>
                    </div>
                    {% comment %} <div>
                        <label for="">Symbol:</label>
                        <select  >
                            <option value="">Select</option>
                        </select>
                    </div> {% endcomment %}
                    <div>
                        <label for=""></label>
                        <button type="submit" value="View" class="form-btn">View</button>
                        <a style="color:#fff !important;padding: 2px 10px; cursor:pointer;" href="{% url 'Admin:manage-trades' %}" class="cancel-btn">Clear</a>
                    </div>
                </div>
            </form>
        </div>
        <div class="trades-body user-table">
            {% comment %} <button class="delete-btn">Delete</button> {% endcomment %}
            <table style="width: 100%;">
                <tr>
                    <th>Username</th>
                    <th>Symbol</th>
                    <th>Type</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    {% comment %} <th>Brk</th>
                    <th>Deal</th> {% endcomment %}
                    <th>Status</th>
                    <th>Order Time</th>
                    {% comment %} <th>Execution Time</th> {% endcomment %}
                    <th>IPAddress</th>
                    {% comment %} <th>DeviceId</th> {% endcomment %}
                    <th>Reference Price</th>
                    <th>Order Method</th>
                </tr>
                {% for i in manage_trades %}
                <tr>
                    <td>{{i.buy_sell_user__user_name}}</td>
                    <td>{{i.coin_name}}</td>
                    {% if i.quantity > 0 %}
                        <td style="color: blue">{{i.action}}</td>
                        <td style="color: blue">{{i.quantity |stringformat:"+d"|slice:"1:"}}</td>
                        <td style="color: blue">{{i.price}}</td>
                    {% else %}
                        <td style="color: red">{{i.action}}</td>
                        <td style="color: red">{{i.quantity |stringformat:"+d"|slice:"1:"}}</td>
                        <td style="color: red">{{i.price}}</td>
                    {% endif %}
                    {% comment %} <td>Brk</td> {% endcomment %}
                    {% comment %} <td>Deal</td> {% endcomment %}
                    {% if i.trade_status != True %}
                        <td>Successful</td>
                    {% else %}
                        <td>Pending</td>
                    {% endif %}
                    <td>{{i.created_at}}</td>
                    {% comment %} <td>Execution Time</td> {% endcomment %}
                    <td>{{i.ip_address}}</td>
                    {% comment %} <td>DeviceId</td> {% endcomment %}
                    <td>{{i.price}}</td>
                    <td>{{i.order_method}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

<script>
    $('.closeBtn').click(function () {
        $(".trades-side").hide();
        $(".trades-body").css("width", "96%");
      });
    
      $('#manageTradesFilterId').click(function () {
        $(".trades-side").show();
        $(".trades-body").css("width", "78%");
      });
</script>

{% endblock content %}

templates/report/trade-account.html
{% extends "index.html" %} {% block content %}

<div class="tab-content" id="tradeaccount">
    <div class="flex">
        <div class="trade-download">
            <div style="transform: rotate(90deg);padding-left: 10px;cursor:pointer;">
                <p id="TradeaccountFilterId">Filter</p>
            </div>
            {% comment %} <span>
                <a href=""><i class="fa-solid fa-file-csv"></i></a>
            </span> {% endcomment %}
        </div>
        <div class="trades-side">
            <div class="trade-top">
                <div class="flex space-bw">
                    <div>
                        <p>Filter</p>
                    </div>
                    <div class="closeBtn">
                        <i class="fa-solid fa-xmark"></i>
                    </div>
                </div>
            </div>
            <div class="trade-btm">
                <div>
                    <label for="">Username:</label>
                    <select  id="tradeUserNameId">
                        <option value="">All Users</option>
                        {% for i in user_obj %}
                            <option value="{{i.user_name}}">{{i.user_name}}</option>
                        {% endfor %}
                    </select>
                </div>
               
                <div>
                    <label for=""></label>
                    <input type="button" value="View" id="tradeBtnId" class="form-btn">
                    <input type="submit" value="Clear" class="cancel-btn" onclick="tradeBtnClear()">
                </div>
            </div>
        </div>
        <div class="trades-body user-table">
            <table style="width: 100%;">
                <tr>
                    <th>Username</th>
                    <th>ParentUser</th>
                    <th>PL</th>
                    <th>Brk</th>
                    <th>Balance</th>
                    <th>Equity</th>
                    <th>Credit</th>
                    <th>Net P/L</th>
                    <th>M2M P/L</th>
                    <th>MarginUsed</th>
                    <th>FreeMargin</th>
                    <th>MarginLevel</th>
                </tr>
                <tbody id="tradeAccountTable">

                </tbody>
               
            </table>
        </div>
    </div>
</div>

<script>

    $('.closeBtn').click(function () {
        $(".trades-side").hide();
        $(".trades-body").css("width", "96%");
      });
    
      $('#TradeaccountFilterId').click(function () {
        $(".trades-side").show();
        $(".trades-body").css("width", "78%");
      });


    function tradeBtnClear(){
        location.href="{% url 'Admin:trade-account' %}"
    }

    const tradeAccountHandler = (user_, user_id="{{user.id}}") =>{

        let m2mListUserWise = [];
        axios.get(`{% url "weekly-admin-api" %}?user_id=${user_id}&user_name=${user_name}`, {headers: { "X-CSRFToken": "{{ csrf_token }}" }})
        .then(res => {
            console.log("res ==", res);
            $("#tradeAccountTable").empty();
            if (res?.data?.result) {
                  axios
                    .post(`${BASE_URL}/api/tradeCoin/weekly`, {
                      identifiers: res?.data?.result?.map(
                        (obj) => obj.identifer
                      ),
                    })
                    .then((res1) => {
                      res?.data?.result.map((mapItem) => {
                          const currentLiveData = res1.data?.response?.find(
                            (liveData) =>
                              liveData?.InstrumentIdentifier === mapItem?.identifer
                          );
                          const currentP_L =
                            mapItem?.total_quantity > 0
                              ? (currentLiveData?.BuyPrice - mapItem?.avg_buy_price) *
                                mapItem?.total_quantity *
                                currentLiveData?.QuotationLot
                              : (mapItem?.avg_sell_price - currentLiveData?.SellPrice) *
                                Math.abs(mapItem?.total_quantity) *
                                currentLiveData?.QuotationLot;
    
                            m2mListUserWise = [
                            ...(m2mListUserWise || []),
                            {
                              user_id: mapItem?.buy_sell_user__id,
                              m2mTotal: currentP_L,
                            },
                          ];
                      });
                    })
            }
    
            setTimeout(() => {
                res.data.release_p_and_l.map(item => {
                    const filterUser = m2mListUserWise?.filter(obj => obj.user_id === item.user_summary__id)
                    const m2mFinal =  Number(
                        filterUser && filterUser.length === 0
                          ? 0
                          : filterUser.length === 1
                          ? filterUser?.[0]?.m2mTotal?.toFixed(2)
                          : filterUser?.reduce((a, b) => a?.m2mTotal + b?.m2mTotal)
                      )?.toFixed(2);
                      const m2mcolor = m2mFinal > 0 ? 'blue' : 'red';
                    $("#tradeAccountTable").append(`
                        <tr>
                            <td>${item.user_summary__user_name}</td>
                            <td>${item.user_summary__parent}</td>
                            <td>0.00</td>
                            <td>0.00</td>
                            <td>0.00</td>
                            <td>${item.user_summary__balance}</td>
                            <td>${item.user_summary__credit}</td>
                            <td style="color: ${item.total_amount >= 0 ? 'blue' : 'red'};">${item.total_amount.toFixed(2)}</td>
                            <td style="color:${m2mcolor}">${isNaN(m2mFinal) ? "0.00" : m2mFinal}</td> 
                            <td>${(isNaN(m2mFinal) ? 0 : Number(m2mFinal) +Number(item.total_amount))?.toFixed(2)}</td>
                            <td>0.00</td>
                            <td>${(isNaN(m2mFinal) ? 0 : Number(m2mFinal) +Number(item.total_amount))?.toFixed(2)}</td>
                        </tr>
                    `);
                });
            }, 1000)
        })
        .catch(err => {
            console.log("err", err);
        });
    }
    tradeAccountHandler();
    $("#tradeBtnId").click(() =>{
        tradeAccountHandler($("#tradeUserNameId").val());
    })
</script>

{% endblock content %}